version: "3.6"

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      CONFIG_FILE_PATH: config.yaml
    restart: on-failure